### ISSUE TITLE
branche 2.3/2.4

### ISSUE THREAD

**Issue by lgeo3** [aldebaran/manifest#1]
Hi, could you please provide the manifest for 2.3 and 2.4 branch (so partners/client could build /link to qimessaging using public toolchain easily).

**Comment by vbarbaresi** [comment]
Done,

> $ qisrc init git@github.com:aldebaran/manifest.git -b release-2.3
> 
> $ qisrc init git@github.com:aldebaran/manifest.git -b release-2.4
